name: Update README

on:
  push:
    paths:
      - "manifest.json"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    # Шаг 3: Запускаем скрипт
    - name: Run PHP script
      run: php ./.github/workflows/update_readme.php

    # Шаг 4: Коммит изменений
    - name: Commit changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add README.md .last_manifest_version
        git commit -m "Update README.md based on manifest.json"
        git push
